# Generated by Django 2.1.7 on 2019-03-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='', max_length=300, primary_key=True, serialize=False, verbose_name='ID Пользователя')),
                ('messenger', models.IntegerField(choices=[(0, 'Telegram'), (1, 'Viber')], verbose_name='Мессенджер')),
                ('read_invitation', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Фамилия')),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
