# Generated by Django 2.1.7 on 2019-11-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='', max_length=300, primary_key=True, serialize=False, verbose_name='ID Пользователя')),
                ('messenger', models.IntegerField(choices=[(0, 'Telegram'), (1, 'Viber'), (2, 'VK'), (3, 'Facebook')], verbose_name='Мессенджер')),
                ('read_invitation', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Фамилия')),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('language', models.IntegerField(choices=[(0, 'Русский'), (1, 'English')], default=0)),
                ('group', models.CharField(default='', max_length=300, verbose_name='Номер группы')),
            ],
        ),
    ]
