# Generated by Django 2.1.7 on 2019-11-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prev_state',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
