# Generated by Django 2.1.7 on 2019-11-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald_bot', '0002_user_prev_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='read_invitation',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_slug',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Телеграм ник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prev_state',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Предыдущее состояние'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Место нахождение пользователя'),
        ),
    ]
